"""Add Composite Index

Revision ID: 1e400645e8d9
Revises: b011e4df1a17
Create Date: 2026-07-06 18:26:55.431505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e400645e8d9'
down_revision: Union[str, Sequence[str], None] = 'b011e4df1a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ticket_status_event_id', 'tickets', ['status', 'event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticket_status_event_id', table_name='tickets')
    # ### end Alembic commands ###
