"""add capacity

Revision ID: 5986d888ce9f
Revises: 6011b9c9f0da
Create Date: 2026-06-30 18:09:23.785069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5986d888ce9f'
down_revision: Union[str, Sequence[str], None] = '6011b9c9f0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('total_capacity', sa.Integer(), nullable=False))
    op.add_column('events', sa.Column('seats_available', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('events', 'seats_available')
    op.drop_column('events', 'total_capacity')
    # ### end Alembic commands ###
